# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='post',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
