# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190405_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', tinymce.models.HTMLField()),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('contact_info', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.User')),
            ],
        ),
    ]
